name=UngulaNetLib
version=0.0.1
author=Alex Conesa
maintainer=alexconesap <alexconesap@gmail.com>
sentence=Networking library for ESP32 (WiFi, HTTP server, WebSocket, HTTP client)
paragraph=WiFi AP, HTTP+WebSocket server, HTTP client for REST APIs. ESP-IDF based, no Arduino dependency.
category=Communication
url=https://github.com/alexconesap/ungula-lib-net.git
includes=ungula_net_lib.h
depends=UngulaGenericLib
architectures=esp32
